version: "3.1"

services:

  gateway:
    image: lifedotio/lifeio-gateway:1.3.0
    env_file:
      - docker-compose.env
    volumes:
      - ./gate:/gate
    ports:
      - "80:80"
      - "443:443"
